### PR TITLE
Privatize functions

### LINKED ISSUE #31: Do not expose private methods
We shouldn't expose some methods to the user:
```
>>> p = b.product().get("5d6d195404cd38000a22ecdd")
>>> dir(p)
['_Component__extract_id', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_build_url_params', '_cls', '_extract_expand', '_id', '_sub_products', 'active', 'api_path', 'build_instance', 'build_resource', 'business_rules', 'company', 'company_take', 'create', 'created', 'currency', 'default_position', 'delete', 'deleted', 'description', 'discount', 'get', 'get_all', 'handle_error', 'human_id', 'id', 'identifier', 'main_product', 'max_distance', 'media', 'modified', 'name', 'parents', 'parse_json', 'path', 'price', 'price_change_percentage', 'properties', 'refresh', 'request', 'search', 'short_description', 'simple_get_query', 'simple_query', 'tags', 'update', 'vat']
```
For instance, `simple_get_query`,`simple_query`, etc..

### PR DESCRIPTION
**Pull request by alchemistake**
Closes #31 
We cannot make function private without some major head aches. So I made them protected. They are still accessible but interpreter and users know that they are for internal use only.
I wish they had package keyword in python :/

### CODE REVIEW

**Comment by alchemistake** [comment]
I ran the tests again just to be sure, "test_refresh_product" fails. Looking at it.

**Comment by alchemistake** [comment]
Master fails with the same test, too.

**Comment by cathoderay** [comment]
Can you find out why it fails?

**Review by cathoderay — APPROVED** [review]
Good job, man! =)

**Pull request merged**
